### ISSUE TITLE
Many error boxes pop up if the RTL is removed or the computer sleeps/restarts

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#324]

**Comment by ac2cz** [comment]
Tried to fix this blind.  Hopefully we now get just one error if the device is pulled out or stops.  Assigned to Burns for testing.

**Comment by ac2cz** [comment]
This is fixed in v1.05s

**Comment by burnsfisher** [comment]
Everything worked just as I would expect pulling out FCDPP or RTL-SDR.  When I pulled out an AirSpy mini I had to dismiss about a dozen error messages.  Not really a problem because the AirSpy mini does not work anyway (still gets 99 or 100% audio missed on either PSK or DUV.

I'll close this and the AirSpy problem hang on its own.

**Comment by ac2cz** [comment]
As a test for the AirSpy, how does SDR# perform at 3M samples per sec with
no decimation?  Does it work well or same as FoxTelem?

I'm trying to determine what to do next, but it won't be in 1.05.

Chris

On Oct 13, 2017 10:19, "Burns Fisher" <notifications@github.com> wrote:

Closed #324 <https://github.com/ac2cz/FoxTelem/issues/324>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ac2cz/FoxTelem/issues/324#event-1292371853>, or mute
the thread

**Comment by burnsfisher** [comment]
It works fine with SDR# at both 3 and 6MPS.  I do note that it seems to default to having the gain turned all the way down, which is fairly insensitive.  However the signal is still findable.  

I don't know if this is relevant, but SDR# offers me the option of Airspy or Airspy HF+.  My Airspy Mini works only with the "Airspy" type.  (The other one says there is no such device).
